# Generated by Django 3.1 on 2020-08-21 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BarberShop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='city',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='complement',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='district',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='number',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='state',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='obs',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='doc',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='employee',
            name='doc',
            field=models.CharField(max_length=11),
        ),
        migrations.CreateModel(
            name='CLient',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('birthday', models.DateField()),
                ('password', models.CharField(max_length=100)),
                ('doc', models.CharField(max_length=11)),
                ('phone', models.CharField(max_length=20)),
                ('cellphone', models.CharField(max_length=20)),
                ('zipcode', models.CharField(max_length=9)),
                ('adress', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=10)),
                ('complement', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('obs', models.TextField()),
                ('company_fk', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BarberShop.company')),
            ],
        ),
    ]
