# Generated by Django 3.1 on 2020-08-21 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BarberShop', '0002_auto_20200820_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='adress',
        ),
    ]
