# Generated by Django 3.1 on 2020-08-21 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarberShop', '0003_remove_employee_adress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='password',
        ),
        migrations.AddField(
            model_name='client',
            name='dateJoined',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
