# Generated by Django 3.1 on 2020-08-22 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BarberShop', '0004_auto_20200820_2300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='procedure',
            old_name='procedure_active',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='procedure',
            old_name='procedure_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='procedure',
            old_name='procedure_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='procedure',
            old_name='procedure_time',
            new_name='time',
        ),
    ]
