# Generated by Django 3.1 on 2020-10-01 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarberShop', '0007_bugbounty'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugbounty',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
