# Generated by Django 3.1 on 2020-10-01 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BarberShop', '0008_bugbounty_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bugbounty',
            old_name='content',
            new_name='subject',
        ),
    ]
