# Generated by Django 3.1 on 2020-10-05 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarberShop', '0009_auto_20201001_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='birthday',
            field=models.CharField(max_length=100),
        ),
    ]
