# Generated by Django 3.1 on 2020-10-30 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BarberShop', '0012_authgroup_authgrouppermissions_authpermission_authuser_authusergroups_authuseruserpermissions_django'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='company_fk',
        ),
        migrations.DeleteModel(
            name='CLient',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
