# Generated by Django 3.1 on 2020-11-26 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BarberShop', '0013_auto_20201030_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='discount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='tax',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appdate', models.CharField(max_length=10)),
                ('apphour', models.CharField(max_length=5)),
                ('total', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='client', to='BarberShop.authuser')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BarberShop.payment')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BarberShop.procedure')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='professional', to='BarberShop.authuser')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BarberShop.status')),
            ],
        ),
    ]
