# Generated by Django 3.1 on 2020-11-06 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BarberShop', '0013_auto_20201030_2006'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BugBounty',
        ),
    ]
