# Generated by Django 3.1 on 2020-11-27 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarberShop', '0019_auto_20201126_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='interval',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
    ]
