# Generated by Django 3.1 on 2020-12-04 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BarberShop', '0014_delete_bugbounty'),
        ('BarberShop', '0020_schedule_interval'),
    ]

    operations = [
    ]
